# Generated by Django 4.2.2 on 2023-06-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('room', models.CharField(default='', max_length=50)),
                ('kitchen', models.CharField(default='', max_length=50)),
                ('bathroom', models.CharField(default='', max_length=50)),
                ('drawing_room', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
